spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${SPRING_DATASOURCE_URL}"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"

server:
  port: "${PORT:8080}"

resilience4j.ratelimiter:
  instances:
    openai-ratelimiter:
      limitForPeriod: 1
      limitRefreshPeriod: 5s
      timeoutDuration: 30s
      registerHealthIndicator: true
      eventConsumerBufferSize: 10

app:

---
spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: newsroom_service
    password: newsroom_service
    url: jdbc:postgresql://localhost:5432/newsroom_service
  config:
    activate:
      on-profile: local

---
spring:
  jpa:
    show-sql: true
  config:
    activate:
      on-profile: test

app: